import type { Metadata, Viewport } from "next";
import "./globals.css";
import { StoreProvider } from "@/lib/store";
import { AuthProvider } from "@/lib/auth";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import MotionFx from "@/components/MotionFx";
import BottomTabs from "@/components/BottomTabs";
import { SITE, OG_IMAGE } from "@/lib/metadata";
import AuthModal from "@/components/AuthModal";
import ProfileSync from "@/components/ProfileSync";
import FunnelGate from "@/components/FunnelGate";
import Analytics from "@/components/Analytics";
import FirstTouch from "@/components/FirstTouch";
import MarketingPixels from "@/components/MarketingPixels";
import ProgressStrip from "@/components/ProgressStrip";

// Kept near the 155-character mark so search results and link previews show it
// whole. The old copy said "Sample data only", which stopped being true once the
// state, federal, and career data were verified against official sources.
const DESCRIPTION =
  "Turn your service and goals into a personal 30/60/90 day plan: benefits to claim, careers that fit, and how to pay for the training. Free. Not the VA.";

export const metadata: Metadata = {
  // Required for a static export: without it, Next cannot resolve the relative
  // image path below into the absolute URL that social crawlers demand.
  metadataBase: new URL(SITE),
  // "./" resolves per-page against metadataBase, so every route gets its own
  // canonical URL - tells Google the vetpathusa.com copy is the real one.
  alternates: { canonical: "./" },
  title: "VetPath - A clear gameplan for life after service",
  description: DESCRIPTION,
  manifest: "/manifest.webmanifest",
  appleWebApp: { capable: true, statusBarStyle: "black-translucent", title: "VetPath" },
  // Chrome deprecated the apple-only meta; it wants this one alongside.
  // The apple variant stays for older iOS home-screen installs.
  other: { "mobile-web-app-capable": "yes" },
  icons: {
    icon: [{ url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    siteName: "VetPath",
    url: SITE,
    title: "VetPath - A clear gameplan for life after service",
    description:
      "Benefits, career paths, and the next 90 days, built around your service and your goals. Free for veterans, and every figure links to an official source.",
    locale: "en_US",
    images: [OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: "VetPath - A clear gameplan for life after service",
    description:
      "Benefits, career paths, and the next 90 days, built around your service and your goals. Free for veterans.",
    images: [OG_IMAGE.url],
  },
};

export const viewport: Viewport = {
  themeColor: "#0F6E56",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

// Registers the offline/app-shell service worker on real hosts (and localhost for testing),
// and keeps it self-updating: check for a new worker on load / focus / periodically, and when
// an updated worker takes control, reload once so the freshly deployed build shows without a
// manual hard refresh. The reload is armed only when a worker already controls the page, so a
// first-time visitor never sees an install-time reload flash.
const SW_REGISTER = `
if ('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost')) {
  window.addEventListener('load', function () {
    var wasControlled = !!navigator.serviceWorker.controller;
    navigator.serviceWorker.register('/sw.js').then(function (reg) {
      reg.update();
      setInterval(function () { reg.update(); }, 30 * 60 * 1000);
      document.addEventListener('visibilitychange', function () {
        if (document.visibilityState === 'visible') reg.update();
      });
    }).catch(function () {});
    if (wasControlled) {
      var refreshing = false;
      navigator.serviceWorker.addEventListener('controllerchange', function () {
        if (refreshing) return;
        refreshing = true;
        window.location.reload();
      });
    }
  });
}
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Fonts and icons are self-hosted (public/fonts, regenerated by the
            fetch-fonts script). No third-party origin sees a visitor load this
            site, the PWA works fully offline, and first paint skips two extra
            DNS+TLS round-trips. The single-file demo keeps its CDN links by
            design - it has no /fonts directory to lean on. */}
        <link
          rel="preload"
          href="/fonts/tabler/tabler-icons.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        {/* The two faces on the first screen (h1/h2 render at weight 500, body
            at 400) - preloading closes most of the swap window the metric
            fallbacks cover. The other weights arrive as the page needs them. */}
        <link rel="preload" href="/fonts/g/fraunces-500n-latin-5.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/fonts/g/inter-400n-latin-15.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="stylesheet" href="/fonts/fonts.css" />
        <link rel="stylesheet" href="/fonts/tabler-icons.css" />
      </head>
      <body>
        <AuthProvider>
          <StoreProvider>
            <MotionFx />
            <Nav />
            <main id="main"><FunnelGate>{children}</FunnelGate></main>
            <Footer />
            <BottomTabs />
            <ProfileSync />
            <AuthModal />
            <Analytics />
            <FirstTouch />
            <MarketingPixels />
            <ProgressStrip />
          </StoreProvider>
        </AuthProvider>
        {/* Register the offline/update service worker only in production builds - running it
            under `next dev` would cache-first the dev chunks and fight hot-reload. */}
        {process.env.NODE_ENV === "production" && (
          <script dangerouslySetInnerHTML={{ __html: SW_REGISTER }} />
        )}
      </body>
    </html>
  );
}
